spring.application.name=bookvault
spring.datasource.url=jdbc:postgresql://localhost:5432/bookvault
spring.datasource.username=postgres
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=9f3kLx91@AbcD!mnoPqRsTuvWxYz1234567890SecureKey
jwt.expiration=3600000
