CREATE TABLE IF NOT EXISTS book (
    id UUID PRIMARY KEY,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(255),
    total_copies INTEGER NOT NULL,
    available_copies INTEGER NOT NULL,
    CONSTRAINT chk_book_total_copies CHECK (total_copies >= 1),
    CONSTRAINT chk_book_available_copies CHECK (available_copies >= 0),
    CONSTRAINT chk_book_available_not_more_than_total CHECK (available_copies <= total_copies)
);

CREATE TABLE IF NOT EXISTS member (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    membership_status VARCHAR(50),
    joined_at TIMESTAMP,
    CONSTRAINT chk_member_status CHECK (membership_status IN ('ACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT chk_user_role CHECK (role IN ('LIBRARIAN', 'MEMBER'))
);

CREATE TABLE IF NOT EXISTS loan (
    id UUID PRIMARY KEY,
    book_id UUID NOT NULL,
    member_id UUID NOT NULL,
    borrowed_at TIMESTAMP,
    due_date TIMESTAMP,
    returned_at TIMESTAMP,
    status VARCHAR(50),
    CONSTRAINT fk_loan_book FOREIGN KEY (book_id) REFERENCES book (id),
    CONSTRAINT fk_loan_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT chk_loan_status CHECK (status IN ('ACTIVE', 'RETURNED', 'OVERDUE'))
);
